### ISSUE TITLE
where could i get skeletonParts.dat and other files?

### ISSUE THREAD

**Issue by galaxyenginneer** [NamanRastogi/Human-Body-Reconstruction#1]
When I run ./learn or HBR_learn.py, I realize i didn't have the skeletonParts.dat file. I couldn't find such file on the http://ai.stanford.edu/~drago/Projects/scape/scape.html website. May I ask where could I get these files?

**Comment by NamanRastogi** [comment]
I cannot share any of the data files created, but you can create the file yourself. You just need to rig the mesh in blender and save the data in the following format.

First line contains two space separated integers: <num_vertices> <num_bones> 
Second line contains <num_vertices> integers: A[0] ... A[<num_vertices> - 1]
Each A[i] stores the (zero based) index of the bone it belongs to.
